# PyTorch Basic

<img src="./Images/PyTorch.jpeg">

PyTorch is an open source machine learning framework developed by Facebook Artificial Intelligence Research (FAIR). It is based on the Torch library and widely used for building and training neural networks. 
It provides two high-level features such as, 1) Its computing of Tensor is similar to Numpy and 2) Automatic calculation of gradients for forward and backward propaagation. Please refer to further information on: https://pytorch.org/

## Contents

 1. Tensor Basic
 2. Tensor with Characteristics
 3. Tensor and Numpy
 4. Tensor Slicing
 5. Tensor Merging
 6. Tensor Calculation
 7. Tensor Casting
 8. Tensor Statistics
 9. Tensor *_like function
 10. Autograd
 11. Backward

In [1]:
import torch
print(torch.__version__)

1.3.0


<img src = "./Images/Tensor.jpg">

Tensor, or a generalization of matrices, is used for neural networks to operate linear algebra, thus it is a essential structures for neural networks calculations. A vector is a 1-dimensional tensor, a matrix is a 2-dimensional tensor and an array with three indices is a 3-dimensional tensor. Image source: http://noaxiom.org/tensor

## 1. Tensor Basic

In [2]:
# 직접 리스트로부터 Tensor 생성
list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
x = torch.Tensor(list)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [3]:
import numpy as np
# numpy로부터 Tensor 생성
numpy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = torch.Tensor(numpy)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [4]:
# torch.FloatTensor()와 같음
# x = torch.Tensor(행, 열)
x = torch.Tensor(3, 2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [5]:
print("Tensor Type: ", type(x))
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size()) # x.shape

Tensor Type:  <class 'torch.Tensor'>
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([3, 2])


## 2. Tensor with Characteristics

In [6]:
x = torch.zeros(5, 3, dtype = torch.int32)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
Tensor Type:  torch.IntTensor
Tensor Size:  torch.Size([5, 3])


In [7]:
x = torch.ones(5, 3)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([5, 3])


In [8]:
# 0과 1 사이의 무작위 숫자로 이뤄진 Tensor
x = torch.rand(5, 3)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[0.0821, 0.6499, 0.8290],
        [0.0334, 0.7159, 0.4815],
        [0.8212, 0.4659, 0.4673],
        [0.4564, 0.4974, 0.0266],
        [0.1655, 0.2637, 0.9425]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([5, 3])


In [9]:
# 0과 9 사이의 무작위 정수형 숫자로 이뤄진 Tensor
x = torch.randint(low = 0, high = 9, size = (2, 3))
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[2, 2, 1],
        [3, 1, 5]])
Tensor Type:  torch.LongTensor
Tensor Size:  torch.Size([2, 3])


In [10]:
# N(0, 1)을 따르는 정규분포에서 추출된 값으로 채워진 Tensor
x = torch.randn(5, 3)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[-1.5710, -0.3374,  1.0654],
        [ 1.1439,  0.6256, -2.4725],
        [-0.0327, -2.7333, -1.0947],
        [ 0.2925, -1.2570, -0.8873],
        [-1.5413,  0.9818, -0.1989]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([5, 3])


In [11]:
x = torch.eye(5, 3)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([5, 3])


In [12]:
x = torch.arange(0, 3, step = 0.5)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([6])


In [13]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([5, 3])


In [14]:
x = torch.FloatTensor(5, 3)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[1.0194e-38, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([5, 3])


In [15]:
x = torch.IntTensor(5, 3)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[7077993, 6226021, 6619236],
        [6357094, 7078005, 6029428],
        [6881384, 7602291, 7471215],
        [3014777, 7405683, 6881388],
        [6619252, 6946861, 7667823]], dtype=torch.int32)
Tensor Type:  torch.IntTensor
Tensor Size:  torch.Size([5, 3])


## 3. Tensor and Numy

In [16]:
import numpy as np

In [17]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x, type(x))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [18]:
x = torch.from_numpy(x)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Tensor Type:  torch.IntTensor
Tensor Size:  torch.Size([2, 3])


In [19]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
x = x.numpy()
print(x)
print("Numpy Type: ", x.dtype)
print("Numpy Size: ", x.size)

[[1. 2. 3.]
 [4. 5. 6.]]
Numpy Type:  float32
Numpy Size:  6


## 4. Tensor Slicing

In [20]:
x = torch.Tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])


In [21]:
# 모든 원소 출력
x[:, :]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

In [22]:
# 2행부터 출력
x[1:, :]

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

In [23]:
# 2열부터 출력
x[:, 1:]

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.],
        [14., 15., 16.]])

In [24]:
# 2행, 1~4열까지 출력
x[1:, 1:4]

tensor([[ 6.,  7.,  8.],
        [10., 11., 12.],
        [14., 15., 16.]])

In [25]:
# 1열 출력
x[0, :]

tensor([1., 2., 3., 4.])

In [26]:
# x를 1행씩 잘라서 배열로 저장
x_rows = torch.split(x, split_size_or_sections = 1, dim = 0)
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]), tensor([[13., 14., 15., 16.]]))


In [27]:
# x를 1열씩 잘라서 배열로 저장
x_cols = torch.split(x, split_size_or_sections = 1, dim = 1)
print(x_cols)

(tensor([[ 1.],
        [ 5.],
        [ 9.],
        [13.]]), tensor([[ 2.],
        [ 6.],
        [10.],
        [14.]]), tensor([[ 3.],
        [ 7.],
        [11.],
        [15.]]), tensor([[ 4.],
        [ 8.],
        [12.],
        [16.]]))


In [28]:
# 위와 같은 결과
torch.chunk(x, chunks = 1, dim = 1)

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]),)

## 5. Torch Merging

In [29]:
# torch.cat : concatenate
# x_rows를 행으로 이어 붙인다.
torch.cat(x_rows, dim = 0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

In [30]:
# x_rows를 열로 이어 붙인다.
torch.cat(x_rows, dim = 1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16.]])

In [31]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
y = torch.FloatTensor([[-1, -2, -3], [-4, -5, -6]])
z1 = torch.cat([x, y], dim = 0)
z2 = torch.cat([x, y], dim = 1)

print(z1)
print(z2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]])


In [32]:
# x_cols를 쌓아 올린다.
x_new = torch.stack(x_cols, dim = 0)
print(x_new)

tensor([[[ 1.],
         [ 5.],
         [ 9.],
         [13.]],

        [[ 2.],
         [ 6.],
         [10.],
         [14.]],

        [[ 3.],
         [ 7.],
         [11.],
         [15.]],

        [[ 4.],
         [ 8.],
         [12.],
         [16.]]])


In [33]:
x = torch.Tensor(([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]))
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [34]:
# 4행 3열로 변경한다.
x.view(4, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [35]:
# 행에 관계 없이 2열로 바꾼다.
x.view(-1, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [36]:
# transpose
x.t()

tensor([[ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.],
        [ 4.,  8., 12.]])

In [37]:
x.view(2, 1, -1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

In [38]:
# 차원이 1인 값을 축소
x.view(2, 1, -1).squeeze()

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [39]:
# dim = 1 자리에 차원을 추가
x.view(2, 1, -1).squeeze().unsqueeze(dim = 1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

## 6. Tensor Calculation

In [40]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
y = torch.Tensor([[1, 1, 1], [2, 2, 2]])
print("x: ", x)
print("y: ", y)

z = torch.add(x, y)
print("z: ", z)

x:  tensor([[1., 2., 3.],
        [4., 5., 6.]])
y:  tensor([[1., 1., 1.],
        [2., 2., 2.]])
z:  tensor([[2., 3., 4.],
        [6., 7., 8.]])


In [41]:
w = torch.add(x, 10)
w

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [42]:
z = torch.mul(x, y)
print("z: ", z)

z:  tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [43]:
z = torch.pow(x, 2)
print("z: ", z)

z:  tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [44]:
z = torch.div(x, 2)
print("z: ", z)

z:  tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])


In [45]:
z = torch.exp(x)
print("z: ", z)

z:  tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])


In [46]:
z = torch.log(x)
print("z: ", z)
print("x.log(): ", x.log())

z:  tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
x.log():  tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [47]:
z = torch.sqrt(x)
print("z: ", z)

z:  tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


## 7. Tensor Casting

In [48]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print("x: ", x)

x:  tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [49]:
x.type(torch.DoubleTensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [50]:
x.double()

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [51]:
x.type(torch.IntTensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [52]:
x.int()

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## 8. Tensor Statistics

In [53]:
x = torch.Tensor([[-1, 2, -3], [4, -5, 6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [54]:
print("x의 합: ", x.sum())
print("x의 최댓값: ", x.max())
print("x의 최솟값: ", x.min())
print("x의 분산: ", x.var())

x의 합:  tensor(3.)
x의 최댓값:  tensor(6.)
x의 최솟값:  tensor(-5.)
x의 분산:  tensor(17.9000)


In [55]:
x.sum().size()

torch.Size([])

In [56]:
print("x의 합: ", x.sum().item())
print("x의 최댓값: ", x.max().item())
print("x의 최솟값: ", x.min().item())
print("x의 분산: ", x.var().item())

x의 합:  3.0
x의 최댓값:  6.0
x의 최솟값:  -5.0
x의 분산:  17.899999618530273


In [57]:
# 행을 기준으로 열의 최댓값을 출력
value, index = x.max(dim = 0)
value

tensor([4., 2., 6.])

In [58]:
# 열을 기준으로 각 행을 정렬
value, index = x.sort(dim = 1)
value

tensor([[-3., -1.,  2.],
        [-5.,  4.,  6.]])

## 9. Tensor *_like function

In [59]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [60]:
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [61]:
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [62]:
y = torch.rand_like(x)
print(y)

tensor([[0.3928, 0.5947, 0.8046],
        [0.2640, 0.5687, 0.9580]])


## 10. Autograd

In [63]:
x = torch.ones(1)
y = torch.ones(1)
x.requires_grad

False

In [64]:
z = x + y
z.requires_grad

False

In [65]:
x.requires_grad_() # underbar는 inplace의 기능이 있음
x.requires_grad

True

In [66]:
z = x + y
z.requires_grad

True

In [67]:
# 역전파 수행
z.backward()
print(x.grad)

tensor([1.])
