# PyTorch Basic

<img src="./Images/PyTorch.jpeg">

**PyTorch** is an open source machine learning framework developed by Facebook Artificial Intelligence Research (FAIR). It is based on the Torch library and widely used for building and training neural networks. <br/>
<br> It provides two high-level features such as, 1) its computing of Tensor is similar to Numpy and 2) automatic calculation of gradients for forward and backward propaagation. <br/>
<br> Further information is provided at,
- [Official Website](https://pytorch.org/)
- [PyTorch: An Imperative Style, High-Performance
Deep Learning Library](https://papers.nips.cc/paper/9015-pytorch-an-imperative-style-high-performance-deep-learning-library.pdf)

<img src = "./Images/Tensor.jpg" width=600>

[Image source](http://noaxiom.org/tensor)

Tensor, or a generalization of matrices, is used for neural networks to operate linear algebra. Thus, it is an essential structure for neural network modelings and computations. 

A vector is a 1-dimensional tensor, a matrix is a 2-dimensional tensor, an array with three indices is a 3-dimensional tensor (RGB color images for example). Hence, PyTorch is built to deal with deep learning task with ease.

In [1]:
import torch
print(torch.__version__)

1.5.1+cpu


## Contents

 1. Tensor Basic
 2. Tensor with Characteristics
 3. Tensor and Numpy
 4. Tensor Slicing
 5. Tensor Merging
 6. Tensor Calculation
 7. Tensor Casting
 8. Tensor Statistics
 9. Tensor *_like function
 10. Autograd
 11. Backward

## 1. Tensor Basic

`torch.Tensor` generates tensors directly from lists

In [2]:
list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
x = torch.Tensor(list)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


`torch.Tensor` also generates tensors from numpy

In [3]:
import numpy as np
numpy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = torch.Tensor(numpy)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


Same as `torch.FloatTensor()` <br/>
`x = torch.Tensor(row, column)`

In [4]:
x = torch.Tensor(3, 2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [5]:
print("Tensor Type: ", type(x))
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())
print("Tensor Size: ", x.shape)

Tensor Type:  <class 'torch.Tensor'>
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([3, 2])
Tensor Size:  torch.Size([3, 2])


## 2. Tensor with Characteristics
`torch.ones` returns a 2D tensor filled with ones and default type (float32)

In [6]:
x = torch.ones(5, 3)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([5, 3])


`torch.zeros` returns a 2D tensor filled with ones and type of int32

In [7]:
x = torch.zeros(5, 3, dtype = torch.int32)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
Tensor Type:  torch.IntTensor
Tensor Size:  torch.Size([5, 3])


`torch.randn` returns a 2D tensor filled with random values from a normal distribution between 0 and 1

In [8]:
x = torch.rand(5, 3)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[8.5781e-01, 3.0895e-01, 8.2391e-01],
        [5.0044e-01, 5.9903e-04, 5.6767e-01],
        [3.2920e-01, 2.5282e-01, 6.6078e-01],
        [5.9970e-01, 3.5263e-01, 9.0611e-02],
        [4.9054e-01, 8.1033e-01, 6.7261e-01]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([5, 3])


`torch.randn` returns a 2D tensor with values from normal distribution 

In [9]:
x = torch.randn(5, 3)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[ 0.4717,  1.5301, -0.0831],
        [ 0.9878,  1.1812,  0.1078],
        [-0.4028, -1.1864,  0.5190],
        [-1.5112, -1.2395, -1.1129],
        [ 0.9137, -0.8890,  0.8853]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([5, 3])


`torch.randint` returns a 2D tensor filled with random integers between `low`(inclusive) and `high`(exclusive)

In [10]:
x = torch.randint(low = 0, high = 9, size = (2, 3))
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[0, 0, 1],
        [1, 1, 6]])
Tensor Type:  torch.LongTensor
Tensor Size:  torch.Size([2, 3])


`torch.eye` returns a 2D tensor with ones on the diagonal and zeros elsewhere

In [11]:
x = torch.eye(4, 4)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([4, 4])


`torch.arange` returns a 1D tensor of size of `(end-start)/step` and filled with values between `start`(inclusive) and `end`(exclusive) and common difference of `step`

In [12]:
x = torch.arange(0, 3, step = 0.5)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([6])


`torch.Tensor` returns a 2D tensor filled with 32-bit floating point

In [13]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([5, 3])


`torch.FloatTensor` returns a 2D tensor filled with 32-bit floating point

In [14]:
x = torch.FloatTensor(5, 3)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[1.0194e-38, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39]])
Tensor Type:  torch.FloatTensor
Tensor Size:  torch.Size([5, 3])


`torch.IntTensor` returns a 2D tensor filled with 32-bit integer (signed)

In [15]:
x = torch.IntTensor(5, 3)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[7274607, 3014748, 7340137],
        [7602297, 7274600, 6029422],
        [7471216, 6684783, 7077993],
        [6226021, 6619236, 6357094],
        [7078005, 6029428, 6881384]], dtype=torch.int32)
Tensor Type:  torch.IntTensor
Tensor Size:  torch.Size([5, 3])


## 3. Tensor and Numy

In [16]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x, type(x))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


`torch.from_numpy` converts `numpy` to `torch`

In [17]:
x = torch.from_numpy(x)
print(x)
print("Tensor Type: ", x.type())
print("Tensor Size: ", x.size())

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
Tensor Type:  torch.IntTensor
Tensor Size:  torch.Size([2, 3])


`numpy()` converts `torch` to `numpy`

In [18]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
x = x.numpy()
print(x)
print("Numpy Type: ", x.dtype)
print("Numpy Size: ", x.size)

[[1. 2. 3.]
 [4. 5. 6.]]
Numpy Type:  float32
Numpy Size:  6


## 4. Tensor Slicing

In [19]:
x = torch.Tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])


Print all values

In [20]:
x[:, :]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

Print from 1st row and all columns

In [21]:
x[1:, :]

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

Print all rows and from 1st column

In [22]:
x[:, 1:]

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.],
        [14., 15., 16.]])

Print from 1st row and from 1st column

In [23]:
x[1:, 1:4]

tensor([[ 6.,  7.,  8.],
        [10., 11., 12.],
        [14., 15., 16.]])

Print only the 0th row

In [24]:
x[0, :]

tensor([1., 2., 3., 4.])

`torch.split` silces x row by row and store it as an array

In [25]:
x_rows = torch.split(x, split_size_or_sections = 1, dim = 0)
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]), tensor([[13., 14., 15., 16.]]))


`torch.split` slices column by column and store it as an array

In [26]:
x_cols = torch.split(x, split_size_or_sections = 1, dim = 1)
print(x_cols)

(tensor([[ 1.],
        [ 5.],
        [ 9.],
        [13.]]), tensor([[ 2.],
        [ 6.],
        [10.],
        [14.]]), tensor([[ 3.],
        [ 7.],
        [11.],
        [15.]]), tensor([[ 4.],
        [ 8.],
        [12.],
        [16.]]))


`torch.chunk` returns the same results as `torch.split`

In [27]:
torch.chunk(x, chunks = 1, dim = 1)

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]),)

## 5. Torch Merging

`torch.cat` serves `concatenation`.

In [28]:
torch.cat(x_rows, dim = 0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

In [29]:
torch.cat(x_rows, dim = 1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
         15., 16.]])

In [30]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
y = torch.FloatTensor([[-1, -2, -3], [-4, -5, -6]])
z1 = torch.cat([x, y], dim = 0)
z2 = torch.cat([x, y], dim = 1)

print(z1)
print(z2)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [-1., -2., -3.],
        [-4., -5., -6.]])
tensor([[ 1.,  2.,  3., -1., -2., -3.],
        [ 4.,  5.,  6., -4., -5., -6.]])


`torch.stack` stacks columns or rows of torch

In [31]:
x_new = torch.stack(x_cols, dim = 0)
print(x_new)

tensor([[[ 1.],
         [ 5.],
         [ 9.],
         [13.]],

        [[ 2.],
         [ 6.],
         [10.],
         [14.]],

        [[ 3.],
         [ 7.],
         [11.],
         [15.]],

        [[ 4.],
         [ 8.],
         [12.],
         [16.]]])


In [32]:
x = torch.Tensor(([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]))
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


`view` converts the shape of torch

In [33]:
x.view(4, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

`view.(-1, x)` converts shape of tensor with 2 columns regardless of its row

In [34]:
x.view(-1, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

`.t()` serves transpose

In [35]:
# transpose
x.t()

tensor([[ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.],
        [ 4.,  8., 12.]])

In [36]:
x.view(2, 1, -1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

`squeeze()` returns a tensor with all the dimensions of the input of size 1 removed.

In [37]:
x.view(2, 1, -1).squeeze()

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

`unsqueeze` returns a new tensor with a dimension of size one inserted at the specified position.

In [38]:
x.view(2, 1, -1).squeeze().unsqueeze(dim = 1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

## 6. Tensor Calculation

In [39]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
y = torch.Tensor([[1, 1, 1], [2, 2, 2]])
print("x: ", x)
print("y: ", y)

z = torch.add(x, y)
print("z: ", z)

x:  tensor([[1., 2., 3.],
        [4., 5., 6.]])
y:  tensor([[1., 1., 1.],
        [2., 2., 2.]])
z:  tensor([[2., 3., 4.],
        [6., 7., 8.]])


In [40]:
w = torch.add(x, 10)
w

tensor([[11., 12., 13.],
        [14., 15., 16.]])

In [41]:
z = torch.mul(x, y)
print("z: ", z)

z:  tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [42]:
z = torch.pow(x, 3)
print("z: ", z)

z:  tensor([[  1.,   8.,  27.],
        [ 64., 125., 216.]])


In [43]:
z = torch.div(x, 2)
print("z: ", z)

z:  tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])


In [44]:
z = torch.exp(x)
print("z: ", z)

z:  tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])


In [45]:
z = torch.log(x)
print("z: ", z)
print("x.log(): ", x.log())

z:  tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
x.log():  tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [46]:
z = torch.sqrt(x)
print("z: ", z)

z:  tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


## 7. Tensor Casting
`x.type(torch.yTensor)` converts type of x to y.

In [47]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print("x: ", x)

x:  tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [48]:
x.type(torch.DoubleTensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [49]:
x.double()

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [50]:
x.type(torch.IntTensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [51]:
x.int()

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## 8. Tensor Statistics

In [52]:
x = torch.Tensor([[-1, 2, -3], [4, -5, 6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [53]:
print("Sum of x: ", x.sum())
print("Maximum value of x: ", x.max())
print("Minimumn value of x: ", x.min())
print("Mean value of x: ", x.mean())
print("Variance value of x: ", x.var())

Sum of x:  tensor(3.)
Maximum value of x:  tensor(6.)
Minimumn value of x:  tensor(-5.)
Mean value of x:  tensor(0.5000)
Variance value of x:  tensor(17.9000)


In [54]:
x.sum().size()

torch.Size([])

In [55]:
print("Sum of x: ", x.sum().item())
print("Maximum of x: ", x.max().item())
print("Minimum of x: ", x.min().item())
print("Mean of x: ", x.mean().item())
print("Variance of x: ", x.var().item())

Sum of x:  3.0
Maximum of x:  6.0
Minimum of x:  -5.0
Mean of x:  0.5
Variance of x:  17.899999618530273


`max` returns a maximum value of each column

In [56]:
value, index = x.max(dim = 0)
value

tensor([4., 2., 6.])

`sort` sorts each row

In [57]:
value, index = x.sort(dim = 1)
value

tensor([[-3., -1.,  2.],
        [-5.,  4.,  6.]])

## 9. Tensor *_like function

`torch.x_like` returns a tensor with same shape

In [58]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [59]:
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [60]:
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [61]:
y = torch.rand_like(x)
print(y)

tensor([[0.6240, 0.0930, 0.8911],
        [0.8487, 0.0192, 0.2926]])


## 10. Autograd
`autograd` serves automatic differentiation to all calculations to torch.

In [62]:
x = torch.ones(1)
y = torch.ones(1)
x.requires_grad

False

In [63]:
z = x + y
z.requires_grad

False

In [64]:
x.requires_grad_()
x.requires_grad

True

In [65]:
z = x + y
z.requires_grad

True

`backward` serves back propagation.

In [66]:
z.backward()
print(x.grad)

tensor([1.])
